baseurl = "http://web.judaicalink.org"
languageCode = "en-us"
title = "JudaicaLink"
metaDataFormat = "toml"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[mediaTypes]
  [mediaTypes."text/htaccess"]
    suffixes = ["htaccess"]

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5